/var/log/php-fpm/*log {
    daily
    size 100M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644 apache apache
    sharedscripts
    postrotate
        /bin/systemctl reload php-fpm > /dev/null 2>&1 || true
    endscript
}
