<?php
/**
 * Admin Bot Functions
 * 관리자 봇 설정 기능
 */

if (!defined('BASE_PATH')) exit('No direct script access allowed');

/**
 * 봇 설정 핸들러
 * @param object $controller Admin controller instance
 * @param string|null $action Action name
 */
function admin_bot_handler($controller, $action = null) {
    // 설정 저장
    if ($action === 'save' && $_SERVER['REQUEST_METHOD'] === 'POST') {
        try {
            $allowedBots = $_POST['allowed_bots'] ?? [];
            
            // 모든 봇을 먼저 is_allowed = 0으로 설정
            getDbUpdate('bot_config', ['is_allowed' => 0], '1=1');
            
            // 선택된 봇들만 is_allowed = 1로 업데이트
            if (!empty($allowedBots)) {
                $placeholders = implode(',', array_fill(0, count($allowedBots), '?'));
                $sql = "UPDATE bot_config SET is_allowed = 1 WHERE user_agent IN ({$placeholders})";
                
                $pdo = getDBConnection();
                $stmt = $pdo->prepare($sql);
                $stmt->execute($allowedBots);
            }
            
            // robots.txt 파일 생성 (DB에서 다시 읽어서 생성)
            admin_bot_generate_robots_txt();
            
            $controller->renderJson(['success' => true, 'message' => 'BOT 설정이 저장되고 robots.txt가 업데이트되었습니다.']);
        } catch (Exception $e) {
            $controller->renderJson(['success' => false, 'message' => '저장 중 오류: ' . $e->getMessage()]);
        }
        return;
    }
    
    // DB에서 봇 목록 가져오기
    $searchBots = getDbArray("SELECT * FROM bot_config WHERE bot_type = 'search' ORDER BY bot_name ASC");
    $aiBots = getDbArray("SELECT * FROM bot_config WHERE bot_type = 'ai' ORDER BY bot_name ASC");
    
    // 허용된 봇의 user_agent 목록
    $allowedBotsData = getDbArray("SELECT user_agent FROM bot_config WHERE is_allowed = 1");
    $allowedBots = array_column($allowedBotsData, 'user_agent');
    
    $data = [
        'title' => 'BOT 설정',
        'searchBots' => $searchBots,
        'aiBots' => $aiBots,
        'allowedBots' => $allowedBots,
        'robotsTxt' => admin_bot_get_robots_txt_content()
    ];
    $controller->renderView('admin/bot', $data);
}

/**
 * robots.txt 파일 생성
 * @param array|null $allowedBots 허용할 봇 목록
 * @return bool
 */
function admin_bot_generate_robots_txt($allowedBots = null) {
    $baseUrl = 'https://' . $_SERVER['HTTP_HOST'];
    $content = "# robots.txt for {$_SERVER['HTTP_HOST']}\n";
    $content .= "# Generated by Admin Panel\n";
    $content .= "# Last updated: " . date('Y-m-d H:i:s') . "\n\n";
    
    // $allowedBots가 없으면 DB에서 가져오기
    if ($allowedBots === null) {
        $allowedBotsData = getDbArray("SELECT user_agent FROM bot_config WHERE is_allowed = 1");
        $allowedBots = array_column($allowedBotsData, 'user_agent');
    }
    
    // DB에서 전체 봇 목록 가져오기
    $allBots = getDbArray("SELECT * FROM bot_config ORDER BY bot_type, bot_name");
    
    // 허용된 봇들
    $content .= "# ========================================\n";
    $content .= "# ALLOWED BOTS (체크된 봇)\n";
    $content .= "# ========================================\n\n";
    
    if (!empty($allowedBots)) {
        foreach ($allowedBots as $bot) {
            $content .= "# {$bot} - ALLOWED\n";
            $content .= "User-agent: {$bot}\n";
            $content .= "Allow: /\n";
            $content .= "Allow: /board/\n";
            $content .= "Allow: /bbs/\n";
            $content .= "Allow: /news/\n";
            $content .= "Disallow: /admin/\n";
            $content .= "Disallow: /member/\n";
            $content .= "Disallow: /api/\n\n";
        }
    }
    
    // 체크 안 된 봇들 명시적으로 차단
    $content .= "# ========================================\n";
    $content .= "# DISALLOWED BOTS (체크 해제된 봇)\n";
    $content .= "# ========================================\n\n";
    
    foreach ($allBots as $bot) {
        $userAgent = $bot['user_agent'];
        // 허용 목록에 없으면 차단
        if (!in_array($userAgent, $allowedBots)) {
            $content .= "# {$bot['bot_name']} - BLOCKED\n";
            $content .= "User-agent: {$userAgent}\n";
            $content .= "Disallow: /\n\n";
        }
    }
    
    // 나머지 모든 봇 차단
    $content .= "# ========================================\n";
    $content .= "# ALL OTHER BOTS (기타 모든 봇 차단)\n";
    $content .= "# ========================================\n\n";
    $content .= "User-agent: *\n";
    $content .= "Disallow: /\n\n";
    
    // Sitemap
    $content .= "# ========================================\n";
    $content .= "# SITEMAP\n";
    $content .= "# ========================================\n\n";
    $content .= "Sitemap: {$baseUrl}/sitemap_index.xml\n";
    
    // 파일 저장
    $robotsFile = BASE_PATH . '/robots.txt';
    $writeResult = file_put_contents($robotsFile, $content);
    
    if ($writeResult !== false) {
        @chmod($robotsFile, 0666);
        return true;
    }
    
    return false;
}

/**
 * 현재 robots.txt 내용 가져오기
 * @return string
 */
function admin_bot_get_robots_txt_content() {
    $robotsFile = BASE_PATH . '/robots.txt';
    if (file_exists($robotsFile)) {
        return file_get_contents($robotsFile);
    }
    return '';
}

/**
 * robots.txt에서 허용된 봇 추출
 * @return array
 */
function admin_bot_extract_allowed_bots_from_robots_txt() {
    $robotsFile = BASE_PATH . '/robots.txt';
    if (!file_exists($robotsFile)) {
        return [];
    }
    
    $content = file_get_contents($robotsFile);
    $allowedBots = [];
    
    // User-agent와 Allow를 찾아서 추출
    $lines = explode("\n", $content);
    $currentBot = null;
    
    foreach ($lines as $line) {
        $line = trim($line);
        
        // User-agent 찾기
        if (preg_match('/^User-agent:\s*(.+)$/i', $line, $matches)) {
            $bot = trim($matches[1]);
            if ($bot !== '*') {
                $currentBot = $bot;
            }
        }
        // Allow 찾기 (현재 봇이 있고 Allow: /가 있으면 허용된 봇)
        elseif ($currentBot && preg_match('/^Allow:\s*\/\s*$/i', $line)) {
            if (!in_array($currentBot, $allowedBots)) {
                $allowedBots[] = $currentBot;
            }
        }
        // Disallow: /가 나오면 현재 봇 초기화 (차단 봇)
        elseif ($currentBot && preg_match('/^Disallow:\s*\/\s*$/i', $line)) {
            $currentBot = null;
        }
    }
    
    return $allowedBots;
}
