#!/bin/bash

echo "=============================================="
echo "🤗 Hugging Face API 설정 가이드"
echo "=============================================="
echo ""
echo "📋 단계별 설정 방법:"
echo ""
echo "1️⃣  Hugging Face 계정 생성"
echo "   https://huggingface.co 방문"
echo "   회원가입 (GitHub/Google 계정으로 가능)"
echo "   ✨ 완전 무료 (무제한)"
echo ""
echo "2️⃣  API 토큰 발급"
echo "   https://huggingface.co/settings/tokens"
echo "   'New token' 클릭"
echo "   이름 입력 (예: ai-shorts-generator)"
echo "   Role: 'read' 선택"
echo "   토큰 복사 (hf_로 시작)"
echo ""
echo "3️⃣  환경 변수 설정 (아래 명령어 실행)"
echo "   export HF_TOKEN='hf_your_token_here'"
echo ""
echo "4️⃣  설정 확인"
echo "   echo \$HF_TOKEN"
echo ""
echo "5️⃣  테스트 실행"
echo "   python3 test_huggingface_api.py"
echo ""
echo "=============================================="
echo "💰 비용 정보"
echo "=============================================="
echo "• 이미지 생성: 완전 무료 (무제한)"
echo "• 계정만 있으면 사용 가능"
echo "• 크레딧/결제 정보 불필요"
echo ""
echo "=============================================="
echo "⚠️  주의사항"
echo "=============================================="
echo "• 대기열 방식: 1~5분 대기 시간"
echo "• 개발/테스트용 최적"
echo "• 프로덕션 환경에서는 Replicate 권장"
echo ""
echo "=============================================="
echo "🆚 Replicate vs Hugging Face"
echo "=============================================="
echo ""
echo "┌────────────────┬──────────────┬──────────────┐"
echo "│ 항목           │ Replicate    │ Hugging Face │"
echo "├────────────────┼──────────────┼──────────────┤"
echo "│ 비용           │ \$5 무료 크레딧 │ 완전 무료    │"
echo "│ 속도           │ 빠름 (30초)  │ 느림 (1~5분) │"
echo "│ 품질           │ 최고         │ 중간         │"
echo "│ 대기열         │ 없음         │ 있음         │"
echo "│ 추천 용도      │ 프로덕션     │ 개발/테스트  │"
echo "└────────────────┴──────────────┴──────────────┘"
echo ""
echo "=============================================="
echo "📚 더 알아보기"
echo "=============================================="
echo "• 문서: https://huggingface.co/docs/api-inference"
echo "• 모델 탐색: https://huggingface.co/models"
echo "• 커뮤니티: https://huggingface.co/join/discord"
echo ""
