#!/bin/bash

echo "=============================================="
echo "🔐 Replicate API 설정 가이드"
echo "=============================================="
echo ""
echo "📋 단계별 설정 방법:"
echo ""
echo "1️⃣  Replicate 계정 생성"
echo "   https://replicate.com 방문"
echo "   회원가입 (GitHub/Google 계정으로 가능)"
echo "   ✨ 초기 무료 크레딧: \$5 제공"
echo ""
echo "2️⃣  API 토큰 발급"
echo "   https://replicate.com/account/api-tokens"
echo "   'Create token' 클릭"
echo "   토큰 복사 (r8_로 시작)"
echo ""
echo "3️⃣  환경 변수 설정 (아래 명령어 실행)"
echo "   export REPLICATE_API_TOKEN='r8_your_token_here'"
echo ""
echo "4️⃣  설정 확인"
echo "   echo \$REPLICATE_API_TOKEN"
echo ""
echo "5️⃣  테스트 실행"
echo "   python3 test_replicate_api.py"
echo ""
echo "=============================================="
echo "💰 비용 정보 (무료 크레딧 소진 후)"
echo "=============================================="
echo "• 이미지 생성 (SDXL): \$0.003/장"
echo "• 영상 생성 (AnimateDiff): \$0.05/10초"
echo "• 쇼츠 1개 (이미지 7장 + 영상): 약 \$0.071"
echo "• 무료 크레딧으로 약 70개 쇼츠 생성 가능"
echo ""
echo "=============================================="
echo "📊 크레딧 모니터링"
echo "=============================================="
echo "https://replicate.com/account/billing"
echo ""
